--sourcing configuration files
require("jason.plugins-setup")
require("jason.plugin-configs.lsp.mason")
require("jason.core.options")
require("jason.core.keymaps")
require("jason.core.colorscheme")
require("jason.plugin-configs.tree-sitter")
require("jason.plugin-configs.transparent")
require("jason.plugin-configs.cmp")
require("jason.plugin-configs.nvim-tree")
require("jason.plugin-configs.lsp.lspsaga")
require("jason.plugin-configs.lsp")
require("jason.plugin-configs.lsp.lspconfig")
require("jason.plugin-configs.lualine")
require("jason.plugin-configs.telescope")
require("jason.plugin-configs.autopairs")
require("jason.plugin-configs.gitintigration")
require("jason.plugin-configs.lsp.null-ls")
require("jason.plugin-configs.toggleterm")
require("jason.plugin-configs.dapui")
require("jason.plugin-configs.debuggin")
require("jason.plugin-configs.debugpython")
require("jason.plugin-configs.dap-mason")
require("jason.plugin-configs.debugpython")
require("jason.plugin-configs.todo")
require("Jason.plugin-configs.catppucin")
require("jason.plugin-configs.tokyonight")
require("jason.plugin-configs.harpoon")
require("jason.plugin-configs.onedark")
require("jason.functions")

--setting cursorline to be an underline
setLine()


