-- vim.cmd.colorscheme "kanagawa-dragon"
-- vim.cmd.colorscheme "vscode"
-- vim.cmd.colorscheme "tokyonight-night"
-- vim.cmd.colorscheme "ayu-dark"
vim.cmd.colorscheme "material-deep-ocean"
-- vim.cmd.colorscheme "base16-schemer-dark"
-- vim.cmd.colorscheme "base16-monokai"
