-- vim.cmd('colorscheme candikrush')
-- vim.cmd('colorscheme tokyonight')
-- vim.cmd('colorscheme gruvbox')
-- vim.cmd('colorscheme rose-pine')
vim.cmd('colorscheme vscode')
-- vim.cmd('colorscheme nightly')
-- vim.cmd('colorscheme onedark')
