require("user.remap")
require("user.plugin-configs.dracula")
require("user.settings")
require("user.plugin-configs.autopairs")
require("user.plugin-configs.which-key")
require("user.plugin-configs.packer")
require("user.plugin-configs.comment")
require("user.plugin-configs.colorizer")
require("user.plugin-configs.dap-mason")
require("user.plugin-configs.dapui")
require("user.plugin-configs.debugging")
require("user.plugin-configs.code-snap")
require("user.plugin-configs.fugitive")
require("user.plugin-configs.gitintigration")
require("user.plugin-configs.harpoon")
require("user.plugin-configs.lsp-zero")
require("user.plugin-configs.lualine")
require("user.plugin-configs.debugpython")
require("user.plugin-configs.telescope")
require("user.plugin-configs.todo-comments")
require("user.plugin-configs.markdownpreview")
require("user.plugin-configs.peek")
require("user.plugin-configs.toggleterm")
require("user.plugin-configs.transparent")
require("user.plugin-configs.tree-sitter")
-- require("user.plugin-configs.hologram")
-- require("user.plugin-configs.telescope-media-viewer")
require("user.plugin-configs.ts-rainbow")
-- require("user.plugin-configs.twoslash-queries")
require("user.plugin-configs.devicons")
require("user.plugin-configs.lightbulb")
-- require("user.plugin-configs.pretty-hover")
require("user.plugin-configs.neotree")
require("user.plugin-configs.onedark")
require("user.plugin-configs.vim-tmux-navigator")
require("user.plugin-configs.zen-mode")
require("user.plugin-configs.cmp")
require("user.plugin-configs.toggle-vtext")
require("user.colorscheme")
require("user.plugin-configs.noice")
require("user.plugin-configs.kanagawa")
-- require("user.plugin-configs.solargraph")
require("user.plugin-configs.scrollEOF")


require('notify').setup({
  stages = 'fade_in_slide_out',
  background_colour = '#000000',
})
